Repository TownyAdvanced/TownyProvinces, pull requests merged in 2023-07, with the labels that each got.

#58 Add biome pricing calculation
  pom.xml
  src/main/java/io/github/townyadvanced/townyprovinces/data/DataHandlerUtil.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/dynmap_display/DisplayProvincesOnDynmapAction.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/land_validation/BiomeType.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/land_validation/LandvalidationTask.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/province_generation/PaintRegionAction.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/province_generation/RegenerateRegionTask.java
  src/main/java/io/github/townyadvanced/townyprovinces/listeners/TownyListener.java
  src/main/java/io/github/townyadvanced/townyprovinces/objects/Province.java
  src/main/java/io/github/townyadvanced/townyprovinces/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townyprovinces/settings/TownyProvincesSettings.java
  src/main/java/io/github/townyadvanced/townyprovinces/util/BiomeUtil.java
Labels: enhancement

#66 Removed biome lookup config
  pom.xml
  src/main/java/io/github/townyadvanced/townyprovinces/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townyprovinces/settings/TownyProvincesSettings.java
  src/main/java/io/github/townyadvanced/townyprovinces/util/BiomeUtil.java
Labels: enhancement

#68 Added reload command
  src/main/java/io/github/townyadvanced/townyprovinces/TownyProvinces.java
  src/main/java/io/github/townyadvanced/townyprovinces/commands/TownyProvincesAdminCommand.java
Labels: enhancement

#69 Added map refresh to reload command
  src/main/java/io/github/townyadvanced/townyprovinces/TownyProvinces.java
Labels: bug

#70 Added conigurable sleep for looking up the biome in the lv job
  pom.xml
  src/main/java/io/github/townyadvanced/townyprovinces/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townyprovinces/settings/TownyProvincesSettings.java
  src/main/java/io/github/townyadvanced/townyprovinces/util/BiomeUtil.java
Labels: enhancement

#74 Added configurable pause to biome lookup
  pom.xml
  src/main/java/io/github/townyadvanced/townyprovinces/settings/ConfigNodes.java
Labels: enhancement

#73 Updated French locale and fixed a typo in the Russian locale
  src/main/resources/lang/fr-FR.yml
  src/main/resources/lang/ru-RU.yml
Labels: enhancement

#77 Updated README
  README.md
Labels: documentation

#78 Outpost integration
  pom.xml
  src/main/java/io/github/townyadvanced/townyprovinces/commands/TownyProvincesAdminCommand.java
  src/main/java/io/github/townyadvanced/townyprovinces/data/DataHandlerUtil.java
  src/main/java/io/github/townyadvanced/townyprovinces/data/TownyProvincesDataHolder.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/dynmap_display/DisplayProvincesOnDynmapAction.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/land_validation/LandvalidationTask.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/province_generation/PaintRegionAction.java
  src/main/java/io/github/townyadvanced/townyprovinces/listeners/TownyListener.java
  src/main/java/io/github/townyadvanced/townyprovinces/objects/Province.java
  src/main/java/io/github/townyadvanced/townyprovinces/objects/ProvinceType.java
  src/main/java/io/github/townyadvanced/townyprovinces/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townyprovinces/settings/TownyProvincesSettings.java
  src/main/resources/lang/en-US.yml
Labels: enhancement

#81 Remove townytravel
  pom.xml
  src/main/java/io/github/townyadvanced/townyprovinces/TownyProvinces.java
  src/main/java/io/github/townyadvanced/townyprovinces/listeners/BukkitListener.java
  src/main/java/io/github/townyadvanced/townyprovinces/listeners/TownyListener.java
  src/main/java/io/github/townyadvanced/townyprovinces/metadata/TownMetaDataController.java
  src/main/java/io/github/townyadvanced/townyprovinces/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townyprovinces/settings/TownyProvincesSettings.java
  src/main/java/io/github/townyadvanced/townyprovinces/util/CustomPlotUtil.java
  src/main/java/io/github/townyadvanced/townyprovinces/util/FastTravelUtil.java
  src/main/resources/lang/en-US.yml
  src/main/resources/lang/fr-FR.yml
Labels: enhancement

#85 Add Province Nation colours
  pom.xml
  src/main/java/io/github/townyadvanced/townyprovinces/data/TownyProvincesDataHolder.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/map_display/DisplayProvincesOnDynmapAction.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/map_display/DisplayProvincesOnMapAction.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/map_display/DisplayProvincesOnPl3xMapV3Action.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/map_display/MapDisplayTask.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/map_display/MapDisplayTaskController.java
  src/main/java/io/github/townyadvanced/townyprovinces/listeners/TownyListener.java
  src/main/java/io/github/townyadvanced/townyprovinces/objects/Province.java
  src/main/java/io/github/townyadvanced/townyprovinces/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townyprovinces/settings/TownyProvincesSettings.java
Labels: enhancement

#88 Fix Pl3xMap v3 stroke and fill colours
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/map_display/DisplayProvincesOnPl3xMapV3Action.java
Labels: bug

#90 Fix prices being sometimes too high on region-border-provinces
  src/main/java/io/github/townyadvanced/townyprovinces/TownyProvinces.java
  src/main/java/io/github/townyadvanced/townyprovinces/commands/TownyProvincesAdminCommand.java
  src/main/java/io/github/townyadvanced/townyprovinces/data/TownyProvincesDataHolder.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/land_validation/LandvalidationTask.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/map_display/DisplayProvincesOnDynmapAction.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/map_display/DisplayProvincesOnMapAction.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/map_display/DisplayProvincesOnPl3xMapV3Action.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/map_display/MapDisplayTask.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/province_generation/PaintRegionAction.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/province_generation/RegenerateRegionTask.java
  src/main/java/io/github/townyadvanced/townyprovinces/objects/Region.java
  src/main/java/io/github/townyadvanced/townyprovinces/settings/ConfigNodes.java
  src/main/java/io/github/townyadvanced/townyprovinces/settings/TownyProvincesSettings.java
  src/main/java/io/github/townyadvanced/townyprovinces/util/FileUtil.java
  src/main/java/io/github/townyadvanced/townyprovinces/util/MoneyUtil.java
Labels: bug

#92 Synch fixes
  src/main/java/io/github/townyadvanced/townyprovinces/TownyProvinces.java
  src/main/java/io/github/townyadvanced/townyprovinces/commands/TownyProvincesAdminCommand.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/land_validation/LandvalidationTask.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/map_display/MapDisplayTask.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/province_generation/RegenerateRegionTask.java
Labels: bug

#89 BlueMap support
  README.md
  pom.xml
  src/main/java/io/github/townyadvanced/townyprovinces/TownyProvinces.java
  src/main/java/io/github/townyadvanced/townyprovinces/jobs/map_display/DisplayProvincesOnBlueMapAction.java
  src/main/java/io/github/townyadvanced/townyprovinces/settings/ConfigNodes.java
  src/main/resources/plugin.yml
Labels: enhancement

#94 Add sick ascii art
  src/main/java/io/github/townyadvanced/townyprovinces/TownyProvinces.java
Labels: documentation
